{
    "appliInfo":{
        "idType":"3",
        "gender":"1",
        "mrrgCode":"20",
        "edu":"70",
        "nationality":"中国",
        "area":"北京市北京市市辖区",
        "incmSrc":"10",
        "hasLoan":"0",
        "name":"善待对方",
        "idNo":"222",
        "birthday":"2017-01-11T16:00:00.000Z",
        "idEDate":"2017-01-11T16:00:00.000Z",
        "occTypeName":"机关机关团体公司行号内勤人员",
        "occType":{
            "firName":"机关",
            "firCode":"00",
            "secName":"机关团体公司行号",
            "secCode":"0001",
            "thiName":"内勤人员",
            "thiCode":"0001001",
            "lvl":"1"
        },
        "height":22,
        "weight":22,
        "mobile":13912345678,
        "tel":22,
        "workDpt":"22",
        "jobTitle":"22",
        "address":"22",
        "zipCode":22,
        "income":22,
        "loanAmt":"",
        "loanRsn":"",
        "incmSrcRmrk":""
    },
    "product":"57ce5eb1a785780c4f4ace5c",
    "mainInfo":{
        "isaFlag":0,
        "benType":"2",
        "tklaksfjxFlag":0,
        "chargeCode":"0",//tantan
        "planCode":"1",
        "unitPremium":6,
        "sumPremium":6,
        "termCode":"终身",//tantan
        "termName":"终身",
        "TKLAKFJRYZXFlag":0,
        "TKLAKFJLWYFlag":0,
        "isaFlag1":1,
        "additionalInfo1":{
            "termCode":"1年"
        },
        "showAmount":6,//tantan
        "sumAmount":6
    },
    "insuredInfo":{
        "insAppRel":"51",
        "idType":"1",
        "mrrgCode":"20",
        "edu":"70",
        "nationality":"中国",
        "area":"北京市北京市市辖区",
        "incmSrc":"10",
        "hasLoan":"0",
        "loanAmt":"",
        "loanRsn":"",
        "name":"斯蒂芬",
        "idNo":"231002198406241019",
        "idEDate":"2017-01-11T16:00:00.000Z",
        "occTypeName":"机关机关团体公司行号内勤人员",
        "occType":{
            "firName":"机关",
            "firCode":"00",
            "secName":"机关团体公司行号",
            "secCode":"0001",
            "thiName":"内勤人员",
            "thiCode":"0001001",
            "lvl":"1"},
            "height":222,
            "weight":222,
            "mobile":13612345678,
            "tel":22,
            "workDpt":"22",
            "jobTitle":"22",
            "address":"22",
            "zipCode":22,
            "income":22,
            "gender":"1",//tantan
            "birthday":"1984-06-23T16:00:00.000Z"//tantan
    },
    "beneInfo1":{
        "benInsRel":"31",
        "idType":"3",
        "gender":"1",
        "percent":"100",
        "name":"阿斯",
        "idNo":"222",
        "birthday":"2017-01-11T16:00:00.000Z"},
        "beneList":[
            {
                "benInsRel":"31",
                "idType":"3",
                "gender":"1",
                "percent":"100",
                "name":"阿斯",
                "idNo":"222",
                "birthday":"2017-01-11T16:00:00.000Z"
            }
        ],
        "addRiskList":[],
        "cardInfo":{
            "bankName":"中国工商银行",
            "cardNo":222222222222222,
            "ownerName":"善待对方"
        },
        "insTgtInfo":{
            "QA0":{"tkgzA":1},
            "QA1":{"tksmA":1}
        },
        "productCode":"TKLAK",
        "additionalInfo1":{
            "termCode":"1年",
            "chargeCode":"1"
        },
        "additionalInfo2":{"otherScheduleCode":"1"}
}
        bluewhale-3 key:gender_undefined|chargeCode_undefined|age_undefined
